job = clean
universe = vanilla
arguments = $(pop_sample)
log = /home/bontrager2/logs/$(job)_$(pop_sample).log
output = /home/bontrager2/logs/$(job)_$(pop_sample).out
error = /home/bontrager2/logs/$(job)_$(pop_sample).err
executable = /home/bontrager2/sub/cleanSam.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 10
transfer_input_files = /home/bontrager2/samtools
# Memory in MBs
request_memory = 8000
# Disk space in KBs
request_disk = 20000000
requirements = (Target.HasGluster == true)

pop_sample = CBE
queue 1

#pop_sample = MAE
#queue 1

#pop_sample = VIE
#queue 1

#pop_sample = MIE
#queue 1
