job = gen_consensus
universe = vanilla
log = /home/bontrager2/logs/$(job)_$(Cluster).log
executable = /home/bontrager2/bin/genConsensus.sh
output = /home/bontrager2/logs/$(job)_$(Cluster)_$(Process).out
error = /home/bontrager2/logs/$(job)_$(Cluster)_$(Process).err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 12
transfer_input_files = /home/bontrager2/samtools
# Memory in MBs
request_memory = 50000
# Disk space in KBs
request_disk = 40000000
requirements = (Target.HasGluster == true)
queue 1
