job = trimmomatic
universe = vanilla
log = /home/bontrager2/logs/$(job)_$(splitbamfile)_$(Cluster).log
executable = /home/bontrager2/sub/trimmomatic.sh
arguments = $(pop_sample)
output = /home/bontrager2/logs/$(job)_$(pop_sample)_$(Cluster).out
error = /home/bontrager2/logs/$(job)_$(pop_sample)_$(Cluster).err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/bontrager2/bin/Trimmomatic-0.36/
request_cpus = 20
# Memory in MBs
request_memory = 32000
# Disk space in KBs
request_disk = 30000000
requirements = (Target.HasGluster == true)

pop_sample = CBE
queue 1
